server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ymjr-core?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 0lxg
#    配置redis集群
  redis:
    database: 1
    timeout: 30000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.159.131:26379
  application:
    name: serviceCore
  cloud:
    nacos:
      server-addr: 192.168.159.131:8848 # nacos地址
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl