server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.159.131:8848 # nacos地址
    gateway:
      routes: # 网关路由配置
        - id: service-core
          uri: lb://serviceCore
          predicates:
            - Path=/*/core/**
          #  - After=2022-09-06T09:16:30.433+08:00[Asia/Shanghai]
        - id: service-sms
          uri: lb://serviceSms
          predicates:
            - Path=/api/sms/**
        - id: service-oss
          uri: lb://serviceOSS
          predicates:
            - Path=/api/qnoss/**